# Generated by Django 5.2.5 on 2026-05-11 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0007_blockeddate_gcal_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddate',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barber.barber'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='blockeddate',
            constraint=models.UniqueConstraint(fields=('barber', 'date'), name='unique_blocked_date_per_barber'),
        ),
    ]
